version: '3'
services:
    django:
        # restart: always
        build: ./django
        volumes:
            - ./django:/django
        ports:
            - '8000:8000'
            - '6006:6006'
        command: ['../wait-for-postgres.sh', 'postgres', 'python3', 'manage.py', 'runserver', '0.0.0.0:8000']
        depends_on:
            - postgres
    postgres:
        build: ./postgresql
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        restart: always
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=api
            - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
